"""The installable app: the React build's manifest, icons, service worker, and SPA routing.

These test the *built* frontend (studybot/backend/app/dist/, generated by `npm run build` in
studybot/frontend — see vite.config.ts). Skipped, not failed, if that build doesn't exist yet: a
backend-only checkout or CI run shouldn't need Node.js just to run pytest.
"""
import json
import re
import struct

import pytest
from fastapi.testclient import TestClient

from app.main import DIST_DIR, create_app
from app.rag.pipeline import StudyBot

pytestmark = pytest.mark.skipif(
    not (DIST_DIR / "index.html").is_file(),
    reason="frontend not built — run `npm run build` in studybot/frontend first",
)


@pytest.fixture
def client(settings, embedder):
    with TestClient(create_app(settings, StudyBot(settings, embedder=embedder))) as anonymous:
        yield anonymous  # deliberately not signed in: these files must be public


def png_size(data: bytes) -> tuple[int, int]:
    assert data[:8] == b"\x89PNG\r\n\x1a\n", "not a PNG"
    return struct.unpack(">II", data[16:24])


def test_manifest_meets_the_install_requirements(client):
    response = client.get("/manifest.webmanifest")
    assert response.status_code == 200
    assert response.headers["content-type"].startswith("application/manifest+json")
    assert response.headers["cache-control"] == "no-cache"
    manifest = response.json()
    assert manifest["name"] == "StudyBot" and manifest["start_url"] == "/" and manifest["scope"] == "/"
    assert manifest["display"] == "standalone"
    assert re.fullmatch(r"#[0-9a-fA-F]{6}", manifest["theme_color"]) and re.fullmatch(r"#[0-9a-fA-F]{6}", manifest["background_color"])
    sizes = {(i["sizes"], i["purpose"]) for i in manifest["icons"]}
    assert ("192x192", "any") in sizes and ("512x512", "any") in sizes and ("512x512", "maskable") in sizes


def test_every_manifest_icon_exists_and_has_the_size_it_claims(client):
    for icon in client.get("/manifest.webmanifest").json()["icons"]:
        image = client.get(icon["src"])
        assert image.status_code == 200 and image.headers["content-type"] == icon["type"] == "image/png", icon["src"]
        width, height = png_size(image.content)
        assert f"{width}x{height}" == icon["sizes"], icon["src"]
    assert png_size(client.get("/icons/apple-touch-icon.png").content) == (180, 180)


def test_the_page_links_the_manifest_and_icons(client):
    html = client.get("/").text
    assert 'rel="manifest" href="/manifest.webmanifest"' in html
    assert 'rel="apple-touch-icon"' in html and 'name="theme-color"' in html
    assert 'name="viewport"' in html


def test_service_worker_is_served_from_the_root_and_never_cached(client):
    response = client.get("/sw.js")
    assert response.status_code == 200
    assert response.headers["content-type"].startswith("text/javascript")
    assert response.headers["cache-control"] == "no-cache", "a cached worker would block updates"
    assert "content-security-policy" in response.headers


def test_service_worker_never_caches_the_api():
    # The one non-negotiable rule (see vite.config.ts's workbox config): auth state, chat streams
    # and every user's own data must always reach the real server, never a cached response.
    # Checked as an actual registerRoute(...) call, not just substrings anywhere in the file —
    # "/api/" and "NetworkOnly" could otherwise both appear without one being routed to the other.
    worker = (DIST_DIR / "sw.js").read_text(encoding="utf-8")
    assert re.search(
        r'registerRoute\(\(\{url:\w+\}\)=>\w+\.pathname\.startsWith\("/api/"\),new \w+\.NetworkOnly',
        worker,
    ), "expected a NetworkOnly route scoped to /api/, not just the substrings anywhere in the file"


def test_every_file_the_worker_precaches_actually_exists(client):
    """A single missing file in the precache manifest makes the whole worker fail to install."""
    worker = (DIST_DIR / "sw.js").read_text(encoding="utf-8")
    manifest = re.search(r"precacheAndRoute\((\[.*?\]),\{\}\)", worker).group(1)
    urls = re.findall(r'url:"([^"]+)"', manifest)
    assert len(urls) >= 5
    for url in urls:
        assert client.get(f"/{url}").status_code == 200, f"{url} is in the worker's precache list but is missing"


def test_the_manifest_is_valid_json_with_no_trailing_junk():
    text = (DIST_DIR / "manifest.webmanifest").read_text(encoding="utf-8")
    assert json.loads(text)["short_name"] == "StudyBot"


# ---- SPA routing --------------------------------------------------------------------------

def test_a_client_side_route_serves_the_app_shell_not_a_404(client):
    # /app/chat/123 isn't a real file — React Router owns it once the page loads.
    response = client.get("/app/chat/123")
    assert response.status_code == 200
    assert "<div id=\"root\">" in response.text


def test_a_hashed_asset_is_served_with_a_year_long_immutable_cache(client):
    js_files = list((DIST_DIR / "assets").glob("index-*.js"))
    assert js_files, "expected at least one hashed JS chunk"
    response = client.get(f"/assets/{js_files[0].name}")
    assert response.status_code == 200
    assert response.headers["cache-control"] == "public, max-age=31536000, immutable"


def test_the_spa_fallback_cannot_be_used_to_read_files_outside_dist(client):
    # full_path is resolved and bounds-checked against DIST_DIR before being treated as a real
    # file — this asks for something that exists on disk (app/config.py) one level above it.
    response = client.get("/..%2fconfig.py")
    assert response.status_code == 200
    assert "<div id=\"root\">" in response.text, "must fall back to the app shell, not leak the source file"
